name: Build and Test Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests-and-coverage:
    name: Run PrivacyGuard tests
    uses: ./.github/workflows/reusable_test.yml
    secrets: inherit
