name: Nightly Cron

on:
  schedule:
    # midnight EST
    - cron:  '0 5 * * *'
  # allow this to be scheduled manually in addition to cron
  workflow_dispatch:

jobs:

  tests-and-coverage-cron:
    name: Test workflow cron job
    uses: ./.github/workflows/reusable_test.yml
    secrets: inherit
