name: Reusable Test Workflow

on:
  workflow_dispatch:
  workflow_call:

jobs:
  tests-and-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
      fail-fast: false
    env:
      # `uv pip ...` requires venv by default. This skips that requirement.
      UV_SYSTEM_PYTHON: 1
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install PrivacyGuard library
      run: |
        uv pip install -e .

    - name: Tests and coverage
      run: |
        pytest --timeout=120
